### ISSUE TITLE
Inaccurate documentation

### ISSUE THREAD

**Issue by kylan11** [green-vulcano/gv-adapter-mongodb#3]
- MongoDB Operation's XML node is said to be called **mongodb-query-call**, which is incorrect and will result in an exception: as you can see in the Activator class, its name is **mongodb-call**.
- The query JSON payload is described as having a two-key structure (collection, query), which is also incorrect: the JSON must only contain the actual JSON Query. The collection in which to perform such query is already defined in the DBO's attributes.
- Furthermore, there is actually **no need to escape " chars**. This has been thoroughly tested.

**Comment by rolag-it** [comment]
Fixed https://github.com/green-vulcano/gv-adapter-mongodb/commit/6f393c35fb5157261418c16dd7b83528a9b4b208
